version: "3.9"
services:
  node:
    build: 
      context: .
      target: run
    container_name: PokeAPI-Node
    restart: always
    ports:
      - '8080:8080'
    links:
      - postgres_database
    depends_on:
      - postgres_database
    environment:
      DB_NAME: pokemon
      DB_PASSWORD: docker
      DB_USER: docker
      DB_HOST: postgres_database
      DB_PORT: 5432
    volumes:
      - ./:/app
    command: bash ./start.sh
  postgres_database:
    image: postgres
    container_name: PokeAPI-Postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pokemon
    ports:
      - '2345:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local